project_id = "yxqbruyeolrrwfolympu"

[functions.whatsapp-mock]
verify_jwt = true

[functions.whatsapp-api]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-dispatch]
verify_jwt = false
