/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedTherapistsRouteImport } from './routes/_authenticated/therapists'
import { Route as AuthenticatedChildrenIndexRouteImport } from './routes/_authenticated/children.index'
import { Route as AuthenticatedChildrenChildIdRouteImport } from './routes/_authenticated/children.$childId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTherapistsRoute = AuthenticatedTherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChildrenIndexRoute =
  AuthenticatedChildrenIndexRouteImport.update({
    id: '/children/',
    path: '/children/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChildrenChildIdRoute =
  AuthenticatedChildrenChildIdRouteImport.update({
    id: '/children/$childId',
    path: '/children/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/therapists': typeof AuthenticatedTherapistsRoute
  '/children/$childId': typeof AuthenticatedChildrenChildIdRoute
  '/children/': typeof AuthenticatedChildrenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/therapists': typeof AuthenticatedTherapistsRoute
  '/children/$childId': typeof AuthenticatedChildrenChildIdRoute
  '/children': typeof AuthenticatedChildrenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/therapists': typeof AuthenticatedTherapistsRoute
  '/_authenticated/children/$childId': typeof AuthenticatedChildrenChildIdRoute
  '/_authenticated/children/': typeof AuthenticatedChildrenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/appointments'
    | '/attendance'
    | '/dashboard'
    | '/rooms'
    | '/therapists'
    | '/children/$childId'
    | '/children/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/appointments'
    | '/attendance'
    | '/dashboard'
    | '/rooms'
    | '/therapists'
    | '/children/$childId'
    | '/children'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/appointments'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/rooms'
    | '/_authenticated/therapists'
    | '/_authenticated/children/$childId'
    | '/_authenticated/children/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/therapists': {
      id: '/_authenticated/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof AuthenticatedTherapistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children/': {
      id: '/_authenticated/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof AuthenticatedChildrenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children/$childId': {
      id: '/_authenticated/children/$childId'
      path: '/children/$childId'
      fullPath: '/children/$childId'
      preLoaderRoute: typeof AuthenticatedChildrenChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedTherapistsRoute: typeof AuthenticatedTherapistsRoute
  AuthenticatedChildrenChildIdRoute: typeof AuthenticatedChildrenChildIdRoute
  AuthenticatedChildrenIndexRoute: typeof AuthenticatedChildrenIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedTherapistsRoute: AuthenticatedTherapistsRoute,
  AuthenticatedChildrenChildIdRoute: AuthenticatedChildrenChildIdRoute,
  AuthenticatedChildrenIndexRoute: AuthenticatedChildrenIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
